sudo: required
services: 
  - docker 

before_install: 
  - docker build -t fentonreid/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fentonreid/docker-react npm test

after_success: 
  - docker build -t fentonreid/multi-client ./client
  - docker build -t fentonreid/multi-nginx ./nginx
  - docker build -t fentonreid/multi-server ./server
  - docker build -t fentonreid/multi-worker ./worker

  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push fentonreid/multi-client 
  - docker push fentonreid/multi-nginx 
  - docker push fentonreid/multi-server
  - docker push fentonreid/multi-worker

# AWS deployment
deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-046566457197'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY